Using accessMode is required in this step of spec, Change also in ake…
akeylesslabs/akeyless-services-helm pull request #21
Opened 2021-01-28 14:17 UTC by MaorPaz

Pleaase review if this configuration is required, @barucoh we talked about it, 
but i just wanted to make everyone else synced

2021-02-01 09:46 UTC, barucoh requested changes

2021-02-01 09:46 UTC, barucoh commented on akeyless-services/templates/persistentVolumeClaims.yaml
> +  accessModes: {{- $.Values.accessMode | toYaml | nindent 2 }}
This change is not needed, the code works.
Just need to enhance the error message.
Please keep the `accessModes` attribute under the `persistance` key.

2021-02-01 10:40 UTC, MaorPaz commented on akeyless-services/templates/persistentVolumeClaims.yaml
> +  accessModes: {{- $.Values.accessMode | toYaml | nindent 2 }}
done

2021-02-01 10:48 UTC, barucoh requested changes

2021-02-01 10:48 UTC, barucoh commented on akeyless-services/values.yaml
> +
Remove

2021-02-01 11:54 UTC, MaorPaz commented on akeyless-services/values.yaml
> +
done

2021-02-01 13:50 UTC, barucoh requested changes

2021-02-01 13:50 UTC, barucoh commented on akeyless-services/values.yaml
> +
This should be removed, not commented out.
This code shouldn't be updated

2021-02-01 16:29 UTC, liorhasson commented on akeyless-services/templates/persistentVolumeClaims.yaml
> +  accessModes: {{- $.Values.persistence.accessMode | toYaml | nindent 2 }}
why?

2021-02-02 07:18 UTC, MaorPaz commented on akeyless-services/values.yaml
> +
Done

2021-02-02 07:32 UTC, MaorPaz commented on akeyless-services/templates/persistentVolumeClaims.yaml
> +  accessModes: {{- $.Values.persistence.accessMode | toYaml | nindent 2 }}
This step is required when setting the persistence volume,

2021-02-02 08:28 UTC, barucoh requested changes
In all honesty, I think this PR can just be closed as it doesn't have any relevant changes...

2021-02-02 08:28 UTC, barucoh commented on akeyless-services/values.yaml
> -env: []
You weren't supposed to remove the `env` key completely, just leave it empty.
This could should not be changed.

2021-02-07 07:54 UTC, MaorPaz commented on akeyless-services/values.yaml
> -env: []
Got it, 
done

2021-02-07 08:21 UTC, closed without merging